version: "3.8"

services:
  backend:
    image: 861821644425.dkr.ecr.eu-north-1.amazonaws.com/eliittilukio-backend
    env_file: .env
    volumes:
      - /data/el-backend:/data
    ports:
      - 127.0.0.1:8002:3000
  frontend:
    image: 861821644425.dkr.ecr.eu-north-1.amazonaws.com/eliittilukio-frontend
    env_file: .env
    ports:
      - 127.0.0.1:8001:8888
