version: "3.8"

services:
  backend:
    image: 861821644425.dkr.ecr.eu-north-1.amazonaws.com/eliittilukio-backend
    env_file: .env
    volumes:
      - /data/el-backend:/data
  frontend:
    image: 861821644425.dkr.ecr.eu-north-1.amazonaws.com/eliittilukio-frontend
    env_file: .env
  caddy:
    image: docker.io/caddy:alpine
    ports:
      - 443:443
    volumes:
      - /data/caddy:/data
      - ./Caddyfile-prod:/etc/caddy/Caddyfile
