version: "3.8"
services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_USER: oe
      MARIADB_PASSWORD: ${DATABASE_PASSWD}
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: oe
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - 3306:3306
